from yacs.config import CfgNode as CN

_C = CN()
_C.OUTPUT_DIR = ''
_C.GPUS = (0,1)
_C.SEED = 233

# Cudnn related params
_C.CUDNN = CN()
_C.CUDNN.BENCHMARK = False
_C.CUDNN.DETERMINISTIC = True
_C.CUDNN.ENABLED = True

# DATASET related params
_C.DATASET = CN()
_C.DATASET.NAME = 'USPTO_50K'
_C.DATASET.ROOT = ''
_C.DATASET.KNOWN_CLASS = False
_C.DATASET.SHARED_VOCAB = True
_C.DATASET.SAMPLE = False
_C.DATASET.AUGMENT = True
_C.DATASET.ADD_3D = False
_C.DATASET.PAD = True
_C.DATASET.MAX_SRC_LENGTH = 256
_C.DATASET.MAX_TRG_LENGTH = 256
_C.DATASET.NUM_VOCAB = 61
_C.DATASET.SRC_PAD_IDX = 0
_C.DATASET.SRC_BOS_IDX = 2
_C.DATASET.SRC_EOS_IDX = 3
_C.DATASET.TRG_PAD_IDX = 0
_C.DATASET.TRG_UNK_IDX = 1
_C.DATASET.TRG_BOS_IDX = 2
_C.DATASET.TRG_EOS_IDX = 3

# common params for NETWORK
_C.MODEL = CN()
_C.MODEL.NAME = ''
_C.MODEL.D_MODEL = 512
_C.MODEL.D_INNER = 2048
_C.MODEL.N_LAYERS = 6
_C.MODEL.N_HEAD = 8
_C.MODEL.SHARED_EMBED = False
_C.MODEL.SHARED_ENCODER = False
_C.MODEL.DROPOUT = 0.1
_C.MODEL.PRETRAINED = ' '
_C.MODEL.D_WORD_VEC = 512
_C.MODEL.D_K = 64
_C.MODEL.D_V = 64
_C.MODEL.N_POSITION = 256
_C.MODEL.TRG_EMB_PRJ_WEIGHT_SHARING = True
_C.MODEL.EMB_SRC_TRG_WEIGHT_SHARING = True
_C.MODEL.SCALE_EMB_OR_PRJ = 'prj'

# common params for TRAIN
_C.TRAIN = CN()
_C.TRAIN.EPOCH = 400
_C.TRAIN.BATCH_SIZE_PER_GPU = 8
_C.TRAIN.ACCUMULATION_STEPS = 1
_C.TRAIN.LEARNING_RATE = 0.1
_C.TRAIN.WARMUP_STEPS = 4000
_C.TRAIN.ADAM_BETA1 = 0.9
_C.TRAIN.ADAM_BETA2 = 0.98
_C.TRAIN.ADAM_EPSILON = 1e-9
_C.TRAIN.NUM_WORKERS = 4
_C.TRAIN.SAVE_MODEL = 'all'
_C.TRAIN.WEIGHT_DECAY = 0.00
_C.TRAIN.LABEL_SMOOTHING = False
_C.TRAIN.CRITERION = "Cross_Entropy"
_C.TRAIN.NUM_SAMPLES = None
_C.TRAIN.SAVE_INTERVAL = 1

# common params for TEST
_C.TEST = CN()
_C.TEST.BATCH_SIZE_PER_GPU = 8
_C.TEST.EVAL_STEPS = 1
_C.TEST.BEAM_SIZE = 1
_C.TEST.TOPK = 5
_C.TEST.SAMPLE_RATIO = 0.1

def update_config(config, args):
    config.defrost()
    config.merge_from_file(args.config)
    config.freeze()
